[project]
name = "ComfyUI-DJ_nodes"
description = "A collection of custom nodes for ComfyUI designed to streamline workflows, specifically for SDXL, quantized models, and prompt management."
version = "1.0.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/magekinnarus/ComfyUI-DJ_nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-DJ_nodes"
Icon = ""
